export const initialValues = {
  // user1: {
  //   profilePhoto: "",
  //   name: "",
  //   phone: "",
  //   gender: "",
  //   email: "",
  // },
  // user2: {
  //   profilePhoto2: "",
  //   name2: "",
  //   phone2: "",
  //   gender2: "",
  //   email2: "",
  // },

  name: "",
  name2: "",
  phone: "",
  phone2: "",
  email: "",
  email2: "",
  gender: "",
  gender2: "",
  profilePhoto: "",
  profilePhoto2: "",

  companyName: "",
  gst: "",
  address: "",
  city: "",
  state: "",
  companyEmail: "",
  companyWhatsappNumber: "",
  website: "",
  businessDetails: "",
  about: "",
  companyPhoto: [],

  membershipType: "yearly",
  category: "",
  startDate: new Date(),
  endDate: new Date(),
  membershipSubscripationFees: "",
  memberBulletingFees: "",
  gstAmount: "",
  amount: 0,
  pendingAmount: "",
  isSubscribeToBulletin: false,
};
