export const initialValues = {
  name: "",
  name2: "",
  phone: "",
  phone2: "",
  email: "",
  email2: "",
  gender: "",
  gender2: "",
  profilePhoto: "",
  profilePhoto2: "",

  companyName: "",
  gst: "",
  address: "",
  city: "",
  state: "",
  companyEmail: "",
  companyWhatsappNumber: "",
  website: "",
  businessDetails: "",
  about: "", 

  membershipType:"petron",
  entryDate:new Date(),
  petronFees:"",  
  petronBulletinFees:"",
  
  membershipType: "yearly",
  category: "",
  startDate: new Date(),
  endDate: new Date(),
  admissionFees:"",
  membershipSubscripationFees: "",
  memberBulletingFees: "",
  otherAmount:"",
  gstAmount: "",
  amount: 0,
  pendingAmount: "",
  isSubscribeToBulletin: false,
};
